{
 "title": "Main Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Fast queue Execution Time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "targets": [
    { "expr": "fastExecutionTimer_seconds_max", "legendFormat": "Fast executionTime" }
   ]
  },
  {
   "title": "Messages per Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queue_messages", "legendFormat": "{{queue}}" }
   ]
  },
  {
   "title": "Slow queue Execution Time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "targets": [
    { "expr": "slowExecutionTimer_seconds_max", "legendFormat": "Slow ExecutionTime" }
   ]
  },
  {
   "title": "Fast execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fastExecutionTime_millis_max" }
   ]
  },
  {
   "title": "Slow execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slowExecutionTime_millis_max" }
   ]
  }
 ]
}